import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/ngnhpadmin">Login</Link>
        </li>
        <li>
          <Link to="/tngquan">Dashboard</Link>
        </li>
        <li>
          <Link to="/dichvu">Service</Link>
        </li>
        <li>
          <Link to="/nhnvin">Staff</Link>
        </li>
        <li>
          <Link to="/nhnvinchitit">Staff Detail</Link>
        </li>
        <li>
          <Link to="/nngk">Apply</Link>
        </li>
        <li>
          <Link to="/nngkchitit">Apply Detail</Link>
        </li>
        <li>
          <Link to="/citchungtab1">Setting</Link>
        </li>
        <li>
          <Link to="/khachhang">Customer</Link>
        </li>
        <li>
          <Link to="/khachhangchitit">Customer Detail</Link>
        </li>
        <li>
          <Link to="/tlch">Schedule</Link>
        </li>
        <li>
          <Link to="/tlchchitit">Schedule Detail</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
